### ISSUE TITLE
How to get load to Deck 1 & 2 working

### ISSUE THREAD

**Issue by byhisdeeds** [22degrees/RoundCorners#30]
Great skin. Love it. I'm currently using the LateNight skin and the load to deck 1 and load to deck 2 buttons on my numark mixtrack pro midi controller work ok. These have no effect in the roundcorners skin. Which files would I need to change to get this working. I want to work on this as I gotta have this skin.

**Comment by 22degrees** [comment]
That's interesting. I will test it.
The controller script for the mixtrack uses the command LoadSelectedTrack.

**Comment by 22degrees** [comment]
Issue confirmed. But I don't know why. 
I will check this on the weekend.

Workaround: use the maximized library view (shortcut: space)

**Comment by 22degrees** [comment]
I think it is fixed with https://github.com/22degrees/RoundCorners/commit/3e2ed8c5084bdd73e121b935579d91041daf056f
@byhisdeeds please check it out

**Comment by byhisdeeds** [comment]
Confirmed that it works now. Wicked!!!!! :)

**Comment by byhisdeeds** [comment]
Closing as fixed

**Comment by 22degrees** [comment]
Thank you very much for reporting and testing!
